import React from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { FileSpreadsheet } from "lucide-react";
import ExcelUpload from "@/components/ExcelUpload";
import { normalizeItemStatus } from "@/lib/itemStatus";

export interface InstrumentsUploadModalProps {
  isOpen: boolean;
  onOpenChange: (open: boolean) => void;
  validationRules: any[];
  rejectedFile: Blob | null;
  setRejectedFile: (file: Blob | null) => void;
  onRefresh: () => void;
}

export function InstrumentsUploadModal({
  isOpen,
  onOpenChange,
  validationRules,
  rejectedFile,
  setRejectedFile,
  onRefresh,
}: InstrumentsUploadModalProps) {
  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-5xl max-h-[95vh] overflow-hidden flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileSpreadsheet size={20} className="text-primary" />
            Bulk Upload Instruments
          </DialogTitle>
          <DialogDescription>
            Upload an Excel file to add multiple instruments at once.
          </DialogDescription>
        </DialogHeader>
        <ExcelUpload
          endpoint="/instruments/bulk-upload"
          mapRow={(row) => {
            const getVal = (aliases: string[]) => {
              const normAliases = aliases.map((a) =>
                a.toLowerCase().replace(/[^a-z0-9]/g, "")
              );
              const key = Object.keys(row || {}).find((k) =>
                normAliases.includes(k.toLowerCase().replace(/[^a-z0-9]/g, ""))
              );
              return key !== undefined ? row[key] : undefined;
            };

            return {
              // sino is auto-generated by backend — not sent from Excel
              name: getVal(["Name", "Description", "NAME OF INSTRUMENT", "Instrument Name"]),
              id_code: getVal(["ID Code", "IMTE", "ID CODE", "Id", "Instrument ID"]),
              range: getVal(["Range", "RANGE"]),
              serial_no: getVal(["Serial No", "SERIAL NO", "Items Sl.No / Model", "Serial Number", "Sl.No"]),
              least_count: getVal(["Least Count", "LEAST COUNT"]),
              location: getVal(["Location", "Item Location", "LOCATION"]),
              frequency: getVal(["Frequency", "CALIB. FREQUENCY in month", "CALIBRATION FREQUENCY", "Calib Frequency"]),
              last_calibration_date: getVal(["Last Calibration Date", "LAST CALIBRATION DATE", "Last Cal. Date", "Last Cal Date"]),
              due_date: getVal(["Due Date", "DUE DATE", "Next Cal. Date", "Next Cal Date"]),
              status: (() => {
                const s = getVal(["Status", "Calibration Status", "STATUS"]);
                if (s && s.toString().trim().toLowerCase() === "active") return "OK";
                return s || "OK";
              })(),
              item_status: (() => {
                const s = getVal(["Item Status", "ITEM STATUS"]);
                return normalizeItemStatus(s);
              })(),
              make: getVal(["Make", "Item Make"]),
              item_type: getVal(["Item Type", "Type"]),
              device_type: (() => {
                const val = getVal([
                  "Device Type",
                  "DEVICE TYPE",
                  "DeviceType",
                  "Type of Device",
                  "Device",
                  "Instrument Type",
                  "Instrument / Gauge",
                  "Category",
                ]);
                if (val) {
                  const str = val.toString().trim();
                  if (/reference|master/i.test(str)) return "Reference Standard";
                  if (/gauge/i.test(str)) return "Gauge";
                  if (/instrument/i.test(str)) return "Instrument";
                  return str;
                }
                const isRef = getVal(["Is Reference Standard", "Is Reference Standar", "Reference Standard"])
                  ?.toString()
                  .toLowerCase();
                if (isRef === "yes" || isRef === "true" || isRef === "1") return "Reference Standard";
                return "Instrument";
              })(),
              part_no: getVal(["Part No", "PART NO", "Part Number"]),
              part_name: getVal(["Part Name"]),
              agency: getVal(["Calibration Agency", "Agency", "CALIBRATION AGENCY AND TC No", "CALIBRATION AGENCY", "Agency Name"]),
              module: getVal(["Module", "Moudle"]),
              calibration_source: getVal(["Calibration Source", "Source"]),
              customer: getVal(["Customer"]),
              sector: getVal(["Sector"]),
              criticality_level: getVal(["Criticality Level", "Criticality"]),
              cert_no: getVal(["Cert. No.", "Cert No", "Certificate No"]),
              notes: getVal(["Notes", "Note"]),
              remarks: getVal(["Remarks", "Remark"]),
              gauge_issue_date: getVal(["Gauge Issue Date", "Issue Date"]),
              gauges_received_by: getVal(["Gauges Received By", "Received By"]),
              gauges_issued_by: getVal(["Gauges Issued By", "Gaues Issued By", "Issued By"]),
              calibration_procedure: getVal(["Calibration Procedure", "Calibration Procedure& Ref Std", "Procedure"]),
              traceable: getVal(["Traceable", "Traceability"]),
              is_reference_standard: (() => {
                const val = getVal(["Is Reference Standard", "Is Reference Standar", "Reference Standard"])
                  ?.toString()
                  .toLowerCase();
                if (val === "yes" || val === "true" || val === "1") return true;
                const devType = getVal([
                  "Device Type",
                  "DEVICE TYPE",
                  "DeviceType",
                  "Type of Device",
                  "Device",
                  "Instrument Type",
                  "Instrument / Gauge",
                  "Category",
                ])
                  ?.toString()
                  .toLowerCase();
                if (devType && (devType.includes("reference") || devType.includes("master"))) return true;
                return false;
              })(),
              custom_parameters: (() => {
                const params: Record<string, any> = {};
                const customRules = validationRules.filter((r) => r.isCustom);
                customRules.forEach((rule) => {
                  const val = getVal([rule.displayName, rule.fieldName, ...(rule.excelAliases || [])]);
                  if (val !== undefined && val !== null && val !== "") {
                    params[rule.fieldName] = val;
                  }
                });
                return params;
              })(),
            };
          }}
          rejectedFile={rejectedFile}
          setRejectedFile={setRejectedFile}
          onRefresh={onRefresh}
          onComplete={() => {
            onRefresh();
            onOpenChange(false);
          }}
        />
      </DialogContent>
    </Dialog>
  );
}
